---@meta

---@alias naughty_signals
---| '"request::display_error"' # Emitted when an error occurred and requires attention.
---| '"added"' # Emitted when a notification is created.
---| '"destroyed"' # Emitted when a notification is destroyed.
---| '"request::display"' # Emitted when a notification has to be displayed.
---| '"request::preset"' # Emitted when a notification needs pre-display configuration.
---| '"request::action_icon"' # Emitted when an action requires an icon it doesn't know.
---| '"request::icon"' # Emitted when a notification icon could not be loaded.
---| '"request::screen"' # Emitted when the screen is not defined or being removed.
